name: Build Windows Executable

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-windows-exe:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Specify the version of Python you need

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install PyInstaller
      run: pip install pyinstaller

    - name: Build Executable
      run: |
        pyinstaller --onefile main.py  # Replace main.py with your entry point file

    - name: Upload Executable
      uses: actions/upload-artifact@v3
      with:
        name: Windows-Executable
        path: dist/main.exe  # Replace main.exe with your generated executable
